### ISSUE TITLE
Form state 

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/JuryInstructions#11]
### User Story
As a developer
I'd like to have a unified state mechanism
So that I can use common code to generate instructions

### Acceptance Criteria
- [x] Back-end functionality to save and serve form-state information easily and efficiently
- [x] PR merged to `master` with the above change.

### Dependencies
| ticket   | link     |
| -------- | -------- |
| Initialize React Project | #5  |

**Comment by Colinstarger** [comment]
Breaking this task up a little -- I think our code should be able to READ instructions from typical instructions and then be able to spit out code for a "put it together" webpage. Note, however, that I suspect that this code would potentially need to be modified since I am not sure at all that the input form -- RTF files, or word files, or even plain text -- are perfectly consistent between instructions.

**Comment by revjtanton** [comment]
@Colinstarger are you suggesting that we consume existing forms to come up with the templates? Is that something we would want for MVP, or could that go into Phase 2?

**Comment by Colinstarger** [comment]
@revjtanton - I don't think "consuming forms" is necessary for MVP, but any architecture we build should have that in mind. I should have been clearer about that. This is a Phase 2 ask, but one worth keeping in mind.

**Comment by revjtanton** [comment]
I've created a second project to work on the importing: https://github.com/CodeForBaltimore/JuryInstructions/projects/2
